language: node_js
node_js:
- "8"  # nodejs的版本
branches:
  only:
  - master  # 设置自动化部署的分支
before_install:
- openssl aes-256-cbc -K $encrypted_062dd552229c_key -iv $encrypted_062dd552229c_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- export TZ='Asia/Shanghai'  
- npm install -g hexo
- npm install -g hexo-cli 
before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "fangzhengcn"
- git config --global user.email jixianfz@gmail.com
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
# - sed -i'' "s~git@github.com:xuezhisd/xuezhisd.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/xuezhisd/xuezhisd.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy
