language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_062dd552229c_key -iv $encrypted_062dd552229c_iv
  -in ./travis/travis.enc -out  ~/.ssh/id_rsa  -d
- chmod 600 ~/.ssh/id_rsa
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "fangzhengcn"
- git config --global user.email jixianfz@gmail.com
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
