language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_062dd552229c_key -iv $encrypted_062dd552229c_iv
  -in .travis/id_rsa_blog.enc -out .travis/id_rsa -d
- export TZ='Asia/Shanghai'
# 设置id_rsa文件权限
- chmod 600 ~/.ssh/id_rsa
# 添加ssh密钥
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
# 添加ssh配置文件
- cp .travis/ssh_config ~/.ssh/config
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "fangzhengcn"
- git config --global user.email 916967300@qq.com
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
